apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-web

spec:
  replicas: 3
  selector:
    matchLabels:
      app: pet-web
  template:
    metadata:
      labels:
        app: pet-web

    spec:
      containers:
        - name: pet-web
          image: icr.io/pet-web/petweb
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
